### ISSUE TITLE
📕 As a user I can see an index of historical figures

### ISSUE THREAD

**Issue by frnpcc** [frnpcc/legends_on_wheels#5]
Feature Checklist:
- [x] Generate the route
- [x] Generate the controller action
- [x] Generate the view
- [x] Test the feature - is it working?
- [x] Add link_to to each card
- [x] Add H2
- [x] Beautify the view - make it look shiny ✨

**Comment by dfvanegas1** [comment]
All done as per what we agreed on 28/02
